version: "3"

# Tool Kompose: for docker-compose to kubernetes cluster deploy conversion => https://github.com/kubernetes/kompose

services:
  base_fastapi_backend:
    build:
      context: ./backend/base_fastapi_backend
    ports:
      - 8080:8080
    command: >
      sh -c "uvicorn run_fastapi_server:app --reload --host 0.0.0.0 --port 8080"
